package jm.task.core.jdbc.dao;

import jm.task.core.jdbc.model.User;
import jm.task.core.jdbc.util.Util;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

import java.util.List;

public class UserDaoHibernateImpl implements UserDao {

    private static final SessionFactory SESSION_FACTORY = Util.getSessionFactory();

    private static final String CREATE_TABLE = "CREATE TABLE IF NOT EXISTS Task_1_4(" +
            "id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
            "name VARCHAR," +
            "lastname VARCHAR," +
            "age INT)";
    private static final String DROP_TABLE = "DROP TABLE IF EXISTS Task_1_4";
    private static final String GET_ALL_USERS = "from User Task_1_4";
    private static final String CLEAN_TABLE = "TRUNCATE TABLE Task_1_4";

    public UserDaoHibernateImpl() {

    }


    @Override
    public void createUsersTable() {
        try (Session session = SESSION_FACTORY.openSession()) {

            session.beginTransaction();
            session.createSQLQuery(CREATE_TABLE).executeUpdate();
            session.getTransaction().commit();

            System.out.println("Таблица создана!");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void dropUsersTable() {
        try (Session session = SESSION_FACTORY.openSession()) {

            session.beginTransaction();
            session.createSQLQuery(DROP_TABLE).executeUpdate();
            session.getTransaction().commit();

            System.out.println("Таблица удалена!");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void saveUser(String name, String lastName, byte age) {

        try (Session session = SESSION_FACTORY.openSession()) {
            session.beginTransaction();

            User user = new User(name, lastName, age);

            session.save(user);
            session.getTransaction().commit();

            System.out.println("User с именем- " + name + " добавлен в базу данных");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void removeUserById(long id) {

        try (Session session = SESSION_FACTORY.openSession()) {
            session.beginTransaction();

            User user = session.get(User.class, id);
            session.remove(user);
            session.getTransaction().commit();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    @Override
    public List<User> getAllUsers() {

        try (Session session = SESSION_FACTORY.openSession()) {
            List<User> users = session.createQuery(GET_ALL_USERS, User.class).getResultList();
            return users;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    @Override
    public void cleanUsersTable() {

        try (Session session = SESSION_FACTORY.openSession()) {
            session.beginTransaction();
            session.createSQLQuery(CLEAN_TABLE).executeUpdate();
            session.getTransaction().commit();

            System.out.println("Таблица очищена!");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
